import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { roboto } from "@/lib/Fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body
        className={`${roboto.className} antialiased relative bg-[--white] dark:bg-[--dark] text-[--dark-gray] dark:text-[--light-gray] transition-all duration-300`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          <Navbar/>
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
